version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  test:
    jobs:
      - cypress/install:
          build: yarn build
      - cypress/run:
          yarn: true
          command: yarn test && yarn test:e2e
